#!/bin/bash

PHP_BIN=$(which php)
inotifywait -rme move,close_write,delete --format "%e %w%f" $MEDIA_PATH | while read file; do
  logname=$(echo "${file}" | awk '{print $2}')
  echo "updating '${logname}'"
  $PHP_BIN artisan koel:sync "${file}"
done
